// Static route-shape checks only. Runtime database/R2 behavior requires an integration environment.
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const read = (path: string) => readFileSync(path, 'utf8')
const presign = read('app/api/admin/documents/presign-file/route.ts')
const register = read('app/api/admin/documents/[id]/register-set/route.ts')
const central = read('app/api/admin/documents/[id]/route.ts')
const linksDelete = read('app/api/admin/documents/[id]/links/[linkId]/route.ts')
const pending = read('lib/documents/pending.ts')
const setZip = read('app/api/admin/documents/[id]/set-zip/route.ts')
const purge = read('lib/documents/ephemeral-attachments.ts')
const cleanup = read('lib/documents/set-upload-cleanup.ts')
const revisionDraft = read('app/api/admin/documents/[id]/revision-drafts/[draftId]/route.ts')
const purgeRoute = read('app/api/admin/documents/purge-ephemeral/route.ts')
const freshMigration = read('scripts/add-document-sets.sql')
const upgradeMigration = read('scripts/upgrade-document-sets-v2.sql')
const rollout = read('scripts/README-document-sets.md')
const leaseUpgradeMigration = read('scripts/upgrade-document-sets-v3-leases.sql')

assert.match(presign, /mainDocumentId/)
assert.match(presign, /setItemKind/)
assert.match(presign, /crypto\.randomUUID\(\)/)
assert.match(presign, /from\('document_set_uploads'\)[\s\S]*\.insert\(/)
assert.match(presign, /cleanupExpiredSetUploads/)
assert.match(presign, /after\(async \(\) =>/)
assert.match(presign, /pruneClaimedSetUploads\(25, 30\)/)
assert.doesNotMatch(presign, /void cleanupExpiredSetUploads/)

assert.match(register, /new HeadObjectCommand/)
assert.match(register, /validateSetUploadClaim/)
assert.match(register, /markSetUploadClaimed/)
assert.match(register, /export const maxDuration = 300/)
assert.match(register, /REGISTER_LEASE_MS = 15 \* 60 \* 1000/)
assert.match(register, /lease_kind: 'register'/)
assert.match(register, /\.eq\('lease_token', leaseToken\)/)
assert.match(register, /\.eq\('link_kind', 'related'\)[\s\S]*\.is\('set_mode', null\)[\s\S]*\.is\('set_draft_id', null\)/)
assert.match(register, /setLink\(mainDocumentId, existingDocumentId, actor, 'linked'\)/)
assert.match(register, /setLink\(mainDocumentId, document\.id, actor, 'registered'\)/)
assert.match(register, /setLink\(mainDocumentId, current\.id, actor, 'revision', draft\.id\)/)

assert.match(central, /getRegistrationSetTransitionBlocker/)
assert.match(central, /findActiveRegistrationSet/)
assert.match(central, /getActiveIncomingDocumentSetMemberships/)
assert.match(central, /validateIncomingSetTransition/)
assert.match(central, /if \(doc\.status === 'Published'\)/)
assert.match(linksDelete, /link\.link_kind === 'set'/)
assert.match(revisionDraft, /getActiveOwnedRevisionSetMemberships/)
assert.match(revisionDraft, /validateIncomingSetTransition/)

assert.match(pending, /set_mode, set_draft_id/)
assert.match(pending, /selectRegistrationSetDraft/)
assert.match(setZip, /set_mode, set_draft_id/)
assert.match(setZip, /selectRegistrationSetDraft/)

assert.match(purge, /isEphemeralSetStorageKey/)
assert.match(purge, /deletedObjectIds/)
assert.doesNotMatch(purge, /\.catch\(\(\) => \{\}\)/)
assert.match(purgeRoute, /export async function POST/)
assert.match(purgeRoute, /documentResult\.data\.status !== 'Published'/)
assert.match(purgeRoute, /status: 500/)
assert.match(purgeRoute, /document\.ephemeral_purge_retry/)

assert.match(cleanup, /lease_kind: 'cleanup'/)
assert.match(cleanup, /releaseCleanupLease/)
assert.match(cleanup, /pruneClaimedSetUploads/)
assert.match(cleanup, /\.eq\('lease_token', leaseToken\)/)

for (const migration of [freshMigration, upgradeMigration]) {
  assert.match(migration, /lease_token\s+uuid/)
  assert.match(migration, /lease_kind\s+text/)
  assert.match(migration, /lease_expires_at\s+timestamptz/)
  assert.match(migration, /idx_document_set_uploads_claimed_retention/)
}
assert.doesNotMatch(upgradeMigration, /ADD COLUMN link_kind/)
assert.match(leaseUpgradeMigration, /ADD COLUMN lease_token uuid/)
assert.match(leaseUpgradeMigration, /ADD COLUMN lease_kind text/)
assert.match(leaseUpgradeMigration, /ADD COLUMN lease_expires_at timestamptz/)
assert.doesNotMatch(leaseUpgradeMigration, /CREATE TABLE document_set_uploads/)
assert.match(rollout, /Deploy the database migration before deploying the application code/)
assert.match(rollout, /Do not run more than one migration script/)
assert.match(rollout, /upgrade-document-sets-v3-leases\.sql/)
