// Static source-shape checks only. These do not claim browser/DOM behavioral coverage.
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const controller = readFileSync('components/documents/useDocumentSetUpload.ts', 'utf8')
const modal = readFileSync('components/documents/DocumentSetUploadModal.tsx', 'utf8')
const phases = readFileSync('components/documents/DocumentSetUploadPhases.tsx', 'utf8')
const client = readFileSync('app/(protected)/staff/documents/DocumentsClient.tsx', 'utf8')

assert.match(controller, /for \(const timer of duplicateTimers\.current\.values\(\)\) clearTimeout\(timer\)/)
assert.match(controller, /for \(const controller of duplicateRequests\.current\.values\(\)\) controller\.abort\(\)/)
assert.match(modal, /document\.addEventListener\('keydown', onDocumentKeyDown, true\)/)
assert.match(modal, /document\.removeEventListener\('keydown', onDocumentKeyDown, true\)/)
assert.match(modal, /previousFocus\?\.focus\(\)/)
assert.match(modal, /useDocumentSetUpload/)
assert.match(phases, /function IntakePhase/)
assert.match(controller, /if \(uploadFailures\.size > 0\)/)
assert.match(controller, /mapBatchUploadFailureOutcomes/)
assert.match(controller, /else if \(prepared\.length > 0\)/)
assert.match(controller, /onDone: \(summary: DocumentSetUploadSummary\) => void/)
assert.match(controller, /const completion: DocumentSetUploadSummary =/)
assert.match(controller, /if \(completion\.failedCount === 0\) onDone\(completion\)/)
assert.match(modal, /onDone: \(summary: DocumentSetUploadSummary\) => void/)
assert.match(modal, /function handleDone\(\) \{[\s\S]*onDone\(\{[\s\S]*successfulCount: controller\.successfulCount[\s\S]*failedCount: controller\.failedCount/)
assert.match(modal, /onClick=\{handleDone\}/)
assert.match(client, /function handleSetUploadDone\(summary: DocumentSetUploadSummary\)/)
assert.match(client, /const feedback = formatDocumentSetUploadCompletion\(summary\)/)
assert.match(client, /toast\(feedback\.message, feedback\.ok\)/)
assert.match(client, /role=\{t\.ok \? 'status' : 'alert'\}/)
assert.match(client, /aria-live=\{t\.ok \? 'polite' : 'assertive'\}/)
assert.match(client, /aria-atomic="true"/)
assert.doesNotMatch(modal, /function IntakePhase|function DocumentSetUploadRow/)
