'use client'

import { useMemo, useState } from 'react'
import type { ChemicalImportRowDTO, ChemicalRegistryRow, ChemicalStorageLocationDTO } from '@/lib/chemical-safety/types'

type Dashboard = { products:number; positions:number; plausibleCandidates:number; mismatches:number; missing:number; quantityConflicts:number; pendingReview:number }
const GROUP_COLORS: Record<string,string> = { A:'#1557C0', B:'#137333', C:'#F04B00', T:'#642A91' }

export function ChemicalSafetyHubClient({ dashboard, locations, registry, imports, canEditUnitIds, canReviewUnitIds }: {
  dashboard: Dashboard; locations: ChemicalStorageLocationDTO[]; registry: ChemicalRegistryRow[]; imports: ChemicalImportRowDTO[];
  canEditUnitIds: string[]; canReviewUnitIds: string[]
}) {
  const [tab, setTab] = useState<'overview'|'layout'|'registry'|'imports'>('overview')
  const [position, setPosition] = useState('')
  const [q, setQ] = useState('')
  const [exporting,setExporting]=useState(false)
  const visible = useMemo(() => registry.filter(row => (!position || row.positionCode === position) && (!q || JSON.stringify([row.canonicalName,row.aliases,row.casNumber]).toLocaleLowerCase('th').includes(q.toLocaleLowerCase('th')))), [registry, position, q])
  const atPosition = (code:string) => registry.filter(row => row.positionCode === code)
  const cards = [
    ['สารเคมี', dashboard.products, 'registry'], ['ตำแหน่งจัดเก็บ', dashboard.positions, 'layout'], ['รอตรวจสอบ', dashboard.pendingReview, 'imports'],
    ['ปริมาณขัดแย้ง', dashboard.quantityConflicts, 'registry'], ['SDS ไม่ตรง', dashboard.mismatches, 'imports'], ['SDS ไม่พบ', dashboard.missing, 'imports'],
  ] as const
  return <main className="chem-hub">
    <style>{`
      .chem-hub{padding:24px;max-width:1600px;margin:0 auto;color:var(--ink)}.chem-hero{padding:28px;border-radius:20px;background:linear-gradient(120deg,#062d52,#0b6380);color:white;box-shadow:0 18px 48px rgba(6,45,82,.2)}.chem-hero small{letter-spacing:.15em;color:#8ff0e9;font-weight:900}.chem-hero h1{margin:7px 0 8px;font-size:34px}.chem-hero p{margin:0;color:#d8edf5}.chem-tabs{display:flex;gap:8px;overflow:auto;margin:18px 0}.chem-tabs button{min-height:44px;padding:0 17px;border:1px solid var(--border);border-radius:10px;background:var(--card);color:var(--ink);font:inherit;font-weight:800;cursor:pointer;white-space:nowrap}.chem-tabs button[aria-selected=true]{background:#0b6380;color:white;border-color:#0b6380}.chem-tabs button:focus-visible,.chem-position:focus-visible,input:focus-visible{outline:3px solid #39bdb4;outline-offset:2px}.chem-metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.chem-metric{min-height:126px;text-align:left;padding:18px;border:1px solid var(--border);border-radius:15px;background:var(--card);cursor:pointer}.chem-metric b{display:block;font-size:34px;color:#0b6380}.chem-layout{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.chem-position{min-height:150px;padding:0;border:1px solid var(--border);border-radius:14px;overflow:hidden;background:var(--card);text-align:left;cursor:pointer}.chem-position header{padding:10px 14px;color:white;font-weight:900}.chem-position div{padding:13px}.chem-position ul{margin:0;padding-left:18px;line-height:1.55}.chem-table-wrap{overflow:auto;border:1px solid var(--border);border-radius:14px;background:var(--card)}.chem-table{width:100%;border-collapse:collapse;min-width:980px}.chem-table th,.chem-table td{padding:12px 14px;border-bottom:1px solid var(--border);text-align:left;vertical-align:top}.chem-table th{font-size:11px;text-transform:uppercase;letter-spacing:.06em;color:var(--muted);background:var(--surface-2)}.chem-conflict{color:#b42318;font-weight:800}.chem-chip{display:inline-flex;padding:3px 8px;border-radius:999px;background:var(--surface-2);font-size:11px;font-weight:800}.chem-filter{display:flex;gap:10px;margin-bottom:12px}.chem-filter input,.chem-filter select{min-height:44px;border:1px solid var(--border);border-radius:10px;background:var(--card);color:var(--ink);padding:0 12px}.chem-import-grid{display:grid;gap:12px}.chem-import{border:1px solid var(--border);border-left:5px solid #0b6380;border-radius:12px;background:var(--card);padding:14px}.chem-import pre{white-space:pre-wrap;word-break:break-word;background:var(--surface-2);padding:10px;border-radius:8px;font-size:11px}.chem-note{padding:12px 14px;border-radius:10px;background:#fff8e7;color:#5c3b00;border:1px solid #f0cf7b}.chem-perm{font-size:12px;color:var(--muted);margin-top:12px}
      @media(max-width:1000px){.chem-layout{grid-template-columns:repeat(2,1fr)}}@media(max-width:650px){.chem-hub{padding:14px}.chem-metrics,.chem-layout{grid-template-columns:1fr}.chem-filter{flex-direction:column}}@media(prefers-reduced-motion:reduce){*{transition:none!important}}
    `}</style>
    <section className="chem-hero"><small>CHEMICAL SAFETY CONTROL ROOM</small><h1>ห้องสารเคมีและทะเบียน SDS</h1><p>ข้อมูลนำเข้าแยกจากข้อมูลอนุมัติ · ใช้ระบบ GHS · ทุกการแก้ไขผ่านผู้ดูแลและผู้ทบทวนคนละคน</p></section>
    <nav className="chem-tabs" aria-label="ส่วนงานห้องสารเคมี">{([['overview','ภาพรวม'],['layout','ผังการจัดเก็บ'],['registry','ทะเบียนสารเคมี'],['imports','ตรวจสอบการนำเข้า']] as const).map(([id,label]) => <button key={id} aria-selected={tab===id} onClick={() => setTab(id)}>{label}</button>)}</nav>
    {tab==='overview' && <><div className="chem-metrics">{cards.map(([label,value,target]) => <button className="chem-metric" key={label} onClick={() => setTab(target)}><span>{label}</span><b>{value}</b></button>)}</div><p className="chem-perm">สิทธิ์ผู้ดูแล {canEditUnitIds.length} หน่วย · สิทธิ์ผู้ทบทวน {canReviewUnitIds.length} หน่วย</p></>}
    {tab==='layout' && <div className="chem-layout">{locations.map(item => <button key={item.id} className="chem-position" onClick={() => {setPosition(item.code);setTab('registry')}}><header style={{background:GROUP_COLORS[item.zoneCode]}}>{item.code}</header><div>{atPosition(item.code).length ? <ul>{atPosition(item.code).map(row => <li key={`${row.productId}-${row.unitId}`}>{row.canonicalName}{row.quantityConflict && ' ⚠'}</li>)}</ul> : <span>ยังไม่มีรายการอนุมัติ</span>}</div></button>)}</div>}
    {tab==='registry' && <><div className="chem-filter"><input aria-label="ค้นหาทะเบียนสารเคมี" value={q} onChange={e=>setQ(e.target.value)} placeholder="ชื่อสาร / alias / CAS"/><select aria-label="ตำแหน่ง" value={position} onChange={e=>setPosition(e.target.value)}><option value="">ทุกตำแหน่ง</option>{locations.map(item=><option key={item.id}>{item.code}</option>)}</select><button disabled={exporting} onClick={()=>{setExporting(true);const p=new URLSearchParams();if(q)p.set('q',q);if(position)p.set('positionCode',position);location.href=`/api/admin/chemical-safety/registry/export?${p}`;setTimeout(()=>setExporting(false),1000)}} style={{minHeight:44,padding:'0 16px',border:0,borderRadius:10,background:'#0b6380',color:'white',fontWeight:800,cursor:'pointer'}}>{exporting?'กำลังสร้าง…':'Export PDF'}</button></div><div className="chem-table-wrap"><table className="chem-table"><thead><tr><th>สารเคมี</th><th>หน่วยงาน / ตำแหน่ง</th><th>ปริมาณ</th><th>SDS</th><th>GHS</th></tr></thead><tbody>{visible.map(row=><tr key={`${row.productId}-${row.unitId}-${row.positionCode}`}><td><b>{row.canonicalName}</b><br/><small>{row.casNumber ? `CAS ${row.casNumber}` : 'ไม่ระบุ CAS'}</small></td><td>{row.unitName}<br/><span className="chem-chip">{row.positionCode||'—'}</span></td><td className={row.quantityConflict?'chem-conflict':''}>{row.reportedTotalRaw||'—'}{row.calculatedTotalValue!=null&&<><br/><small>คำนวณ: {row.calculatedTotalValue} {row.calculatedTotalUnit}</small></>}{row.quantityConflict&&<><br/>⚠ ต้องตรวจสอบ</>}</td><td><span className="chem-chip">{row.sdsStatus}</span></td><td>{row.pictogramCodes.join(', ')||'—'}</td></tr>)}</tbody></table></div></>}
    {tab==='imports' && <><p className="chem-note">รายการ candidate/mismatch/missing ยังไม่ใช่ SDS ที่อนุมัติ ห้ามอนุมัติจากชื่อไฟล์เพียงอย่างเดียว</p><div className="chem-import-grid">{imports.map(row=><article className="chem-import" key={row.id}><b>แถว {row.rowKey} · {row.matchStatus}</b>{row.conflictCodes.length>0&&<p className="chem-conflict">{row.conflictCodes.join(', ')}</p>}<pre>{JSON.stringify({raw:row.rawData,proposal:row.normalizedData},null,2)}</pre></article>)}</div></>}
  </main>
}
