'use client'

import { useMemo, useState } from 'react'
import type { ChemicalSdsDTO } from '@/lib/chemical-safety/types'

export function SdsManagementClient({ items }: { items: ChemicalSdsDTO[] }) {
  const [q,setQ]=useState(''); const [status,setStatus]=useState('')
  const rows=useMemo(()=>items.filter(item=>(!status||item.status===status)&&(!q||JSON.stringify(item).toLocaleLowerCase('th').includes(q.toLocaleLowerCase('th')))),[items,q,status])
  return <main style={{padding:24,maxWidth:1500,margin:'0 auto'}}><section style={{padding:26,borderRadius:18,background:'linear-gradient(120deg,#082f49,#0e7490)',color:'white'}}><small style={{letterSpacing:'.14em',fontWeight:800}}>PRIVATE SDS WORKFLOW</small><h1 style={{margin:'8px 0'}}>จัดการ SDS และข้อมูล GHS</h1><p>ฉบับร่าง → ส่งทบทวน → อนุมัติโดยบุคคลอื่น · ไฟล์จัดเก็บแบบ private</p></section><div style={{display:'flex',gap:10,margin:'18px 0'}}><input aria-label="ค้นหา SDS" value={q} onChange={e=>setQ(e.target.value)} placeholder="ชื่อสาร ผู้ผลิต ภาษา" style={{minHeight:44,flex:1,padding:'0 12px',border:'1px solid var(--border)',borderRadius:10,background:'var(--card)',color:'var(--ink)'}}/><select aria-label="สถานะ SDS" value={status} onChange={e=>setStatus(e.target.value)} style={{minHeight:44,padding:'0 12px',border:'1px solid var(--border)',borderRadius:10,background:'var(--card)',color:'var(--ink)'}}><option value="">ทุกสถานะ</option>{['draft','in_review','approved','superseded','rejected'].map(x=><option key={x}>{x}</option>)}</select></div><div style={{display:'grid',gap:12}}>{rows.map(item=><article key={item.id} style={{padding:16,border:'1px solid var(--border)',borderLeft:`5px solid ${item.status==='approved'?'#16803a':'#d39b16'}`,borderRadius:12,background:'var(--card)'}}><div style={{display:'flex',justifyContent:'space-between',gap:16}}><div><b>SDS {item.revisionLabel||'ไม่ระบุฉบับ'}</b><p style={{margin:'5px 0',color:'var(--muted)'}}>{item.manufacturer||'ไม่ระบุผู้ผลิต'} · {item.language||'—'} · {item.effectiveOn||'—'}</p></div><strong>{item.status}</strong></div><p>GHS: {item.pictogramCodes.join(', ')||'ยังไม่บันทึก'} · H statements {item.hStatements.length} รายการ</p>{item.fileUrl&&<a href={item.fileUrl} target="_blank" rel="noopener noreferrer">เปิดไฟล์แบบ private</a>}</article>)}</div></main>
}
