export function EvacuationStyles() {
  return <style>{`
    .evac-page{--evac-accent:#f97316;--evac-accent-soft:#fff7ed;--evac-ink:#334155;--evac-muted:#64748b;display:grid;gap:14px;min-width:0;color:var(--ink)}
    .evac-page :where(button,input,select,textarea,a):focus-visible{outline:3px solid color-mix(in srgb,var(--primary) 42%,transparent);outline-offset:2px}
    .evac-tabs{display:flex;gap:6px;overflow-x:auto;padding:4px;border:1px solid var(--border);border-radius:12px;background:var(--surface-2);scrollbar-width:thin}
    .evac-tabs button{display:inline-flex;align-items:center;justify-content:center;gap:7px;min-height:44px;flex:0 0 auto;padding:8px 14px;border:1px solid transparent;border-radius:9px;background:transparent;color:var(--muted);font:inherit;font-weight:700;cursor:pointer;white-space:nowrap}
    .evac-tabs button[aria-selected="true"]{border-color:var(--border);background:var(--card);color:var(--primary);box-shadow:inset 0 -2px 0 var(--primary)}
    .evac-panel{display:grid;gap:14px;min-width:0}
    .evac-toolbar,.evac-actions,.evac-card-head,.evac-inline{display:flex;align-items:center;justify-content:space-between;gap:8px;flex-wrap:wrap}
    .evac-actions{justify-content:flex-start}.evac-toolbar{align-items:flex-start}
    .evac-card,.evac-form,.evac-callout{border:1px solid var(--border);border-radius:12px;background:var(--card);padding:14px;min-width:0}
    .evac-card{display:grid;gap:10px}.evac-card h2,.evac-card h3,.evac-card p{margin:0}.evac-card h2{font-size:17px}.evac-card h3{font-size:14px}.evac-card p,.evac-help,.evac-muted{color:var(--muted);font-size:13px;line-height:1.55}
    .evac-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.evac-grid-2{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.evac-grid-3{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}
    .evac-metric{display:grid;gap:4px;min-height:104px;padding:14px;border:1px solid var(--border);border-radius:12px;background:var(--card)}.evac-metric span{color:var(--muted);font-size:12px;font-weight:700}.evac-metric strong{font-size:27px;line-height:1.1;color:var(--ink)}.evac-metric small{color:var(--muted);font-size:11px}
    .evac-status{display:inline-flex;align-items:center;min-height:26px;padding:3px 9px;border-radius:999px;font-size:11px;font-weight:800;line-height:1.3}.evac-status[data-tone="green"]{background:#ecfdf3;color:#15803d}.evac-status[data-tone="amber"]{background:#fffbeb;color:#b45309}.evac-status[data-tone="red"]{background:#fef2f2;color:#b91c1c}.evac-status[data-tone="blue"]{background:#eff6ff;color:#1d4ed8}.evac-status[data-tone="gray"]{background:var(--surface-2);color:var(--muted)}
    .evac-callout{display:grid;gap:6px;border-left:4px solid var(--evac-accent);background:var(--evac-accent-soft)}.evac-callout[data-tone="danger"]{border-left-color:var(--danger);background:color-mix(in srgb,var(--danger) 8%,var(--card))}.evac-callout strong{font-size:14px}.evac-callout span{color:var(--muted);font-size:13px;line-height:1.5}
    .evac-form{display:grid;gap:12px}.evac-form h2,.evac-form h3{margin:0}.evac-form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.evac-form-grid-3{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.evac-form label{display:grid;gap:5px;color:var(--muted);font-size:12px;font-weight:700}.evac-form input,.evac-form select,.evac-form textarea{width:100%;min-height:44px;padding:9px 10px;border:1px solid var(--border);border-radius:8px;background:var(--card);color:var(--ink);font:inherit}.evac-form textarea{min-height:84px;resize:vertical}.evac-form input:disabled,.evac-form select:disabled{background:var(--surface-2)}
    .evac-assignment{display:grid;gap:9px;padding:12px;border:1px solid var(--border);border-radius:10px;background:var(--surface-2)}.evac-assignment-head{display:flex;align-items:center;justify-content:space-between;gap:8px}.evac-assignment-head strong{font-size:13px}.evac-assignment-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px}.evac-assignment-grid label{font-size:11px}
    .evac-list{display:grid;gap:8px;max-height:520px;overflow:auto}.evac-list-item{display:grid;gap:5px;padding:11px;border:1px solid var(--border);border-radius:10px;background:var(--card);color:var(--ink);text-align:left;cursor:pointer}.evac-list-item[data-selected="true"]{border-color:var(--primary);background:var(--primary-soft);box-shadow:inset 4px 0 0 var(--primary)}.evac-list-item strong{font-size:13px}.evac-list-item small{color:var(--muted);font-size:11px;line-height:1.45}
    .evac-table-wrap{overflow-x:auto;border:1px solid var(--border);border-radius:10px}.evac-table{width:100%;border-collapse:collapse;min-width:680px}.evac-table th,.evac-table td{padding:10px;border-bottom:1px solid var(--border);text-align:left;vertical-align:top;font-size:12px}.evac-table th{background:var(--surface-2);color:var(--muted);font-size:11px}.evac-table tr:last-child td{border-bottom:0}.evac-table a,.evac-link{color:var(--primary);font-weight:700;text-decoration:none}.evac-table a:hover,.evac-link:hover{text-decoration:underline}
    .evac-point-grid{display:grid;grid-template-columns:minmax(220px,.8fr) minmax(0,1.2fr);gap:12px;align-items:start}.evac-point-detail{display:grid;gap:10px}.evac-point-detail iframe{width:100%;aspect-ratio:16/9;border:0;border-radius:9px}.evac-photo{display:block;width:100%;max-height:360px;object-fit:contain;border:1px solid var(--border);border-radius:9px;background:var(--surface-2)}
    .evac-empty{display:grid;place-items:center;min-height:150px;padding:20px;border:1px dashed var(--border);border-radius:10px;color:var(--muted);text-align:center}.evac-empty p{margin:0;max-width:430px;font-size:13px;line-height:1.55}.evac-alert{min-height:44px;padding:10px 12px;border:1px solid color-mix(in srgb,var(--danger) 35%,var(--border));border-radius:9px;background:color-mix(in srgb,var(--danger) 8%,var(--card));color:var(--danger);font-size:13px;line-height:1.5}.evac-notice{min-height:44px;padding:10px 12px;border:1px solid color-mix(in srgb,var(--success) 35%,var(--border));border-radius:9px;background:color-mix(in srgb,var(--success) 8%,var(--card));color:var(--success);font-size:13px;line-height:1.5}
    .evac-page .evac-button{min-height:44px}.evac-route-note{display:grid;gap:4px;padding:9px 10px;border-radius:8px;background:var(--primary-soft);color:var(--primary);font-size:12px;line-height:1.45}.evac-route-note strong{font-size:12px}.evac-checks{display:flex;gap:8px;flex-wrap:wrap}.evac-checks label{display:flex;align-items:center;gap:6px;min-height:44px;padding:7px 10px;border:1px solid var(--border);border-radius:8px;background:var(--card);color:var(--ink);font-size:12px;font-weight:700}.evac-checks input{width:18px;height:18px;min-height:0}
    .evac-print-only{display:none}.evac-skeleton{min-height:130px;border-radius:12px;background:var(--surface-2);color:var(--muted);display:grid;place-items:center;font-size:13px}
    @media(max-width:1023px){.evac-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.evac-grid-3{grid-template-columns:repeat(2,minmax(0,1fr))}.evac-point-grid{grid-template-columns:1fr}}
    @media(max-width:767px){.evac-grid,.evac-grid-2,.evac-grid-3,.evac-form-grid,.evac-form-grid-3,.evac-assignment-grid{grid-template-columns:1fr}.evac-card,.evac-form,.evac-callout{padding:12px}.evac-list{max-height:none;overflow:visible}.evac-table-wrap{margin-inline:-2px}.evac-toolbar{display:grid}.evac-toolbar>*{width:100%}.evac-tabs{margin-inline:-2px}.evac-metric{min-height:92px}.evac-actions{display:grid;grid-template-columns:1fr}.evac-actions>*{width:100%}.evac-print-only{display:none}}
    @media(prefers-reduced-motion:reduce){.evac-page *{scroll-behavior:auto!important;transition:none!important;animation:none!important}}
    @media print{.evac-page{display:block}.evac-tabs,.evac-toolbar,.evac-actions,.evac-form,.evac-point-detail .evac-form{display:none!important}.evac-card,.evac-metric{break-inside:avoid;box-shadow:none}.evac-print-only{display:block}.evac-table-wrap{overflow:visible}.evac-table{min-width:0}}
  `}</style>
}
