export function SafetyAssetsStyles() {
  return <style>{`
    .safety-page{--safety-touch-target:44px;display:flex;flex-direction:column;gap:14px;min-width:0}
    .safety-tabs{display:flex;gap:6px;flex-wrap:wrap}
    .safety-tabs button,.safety-toolbar button,.safety-card{min-height:var(--safety-touch-target)}
    .safety-tabs button{border:1px solid var(--border);border-radius:9px;padding:8px 14px;background:var(--card);color:var(--ink);font:inherit;font-weight:650;cursor:pointer}
    .safety-tabs button[aria-selected="true"]{background:var(--primary);border-color:var(--primary);color:#fff}
    .safety-workspace{display:grid;grid-template-columns:minmax(0,1.35fr) minmax(320px,.65fr);gap:12px;align-items:start}
    .safety-sidebar{display:flex;flex-direction:column;gap:10px;min-width:0}
    .safety-toolbar{display:grid;grid-template-columns:minmax(140px,1fr) auto;gap:8px}
    .safety-toolbar input,.safety-toolbar select,.safety-form input,.safety-form select,.safety-form textarea{width:100%;min-height:44px;border:1px solid var(--border);border-radius:8px;background:var(--card);color:var(--ink);padding:8px 10px;font:inherit}
    .safety-filter-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:7px}.safety-filter-grid select{width:100%;min-height:44px;border:1px solid var(--border);border-radius:8px;background:var(--card);color:var(--ink);padding:8px;font:inherit}
    .safety-form textarea{min-height:76px;resize:vertical}
    .safety-list{display:flex;flex-direction:column;gap:7px;max-height:560px;overflow:auto;overscroll-behavior:contain;padding:1px;content-visibility:auto}
    .safety-card{display:block;min-height:78px;width:100%;text-align:left;border:1px solid var(--border);border-radius:10px;background:var(--card);color:var(--ink);padding:10px;cursor:pointer;transition:border-color .15s,background .15s,box-shadow .15s}
    .safety-card:hover,.safety-card[data-selected="true"]{border-color:var(--primary);background:var(--primary-soft);box-shadow:inset 4px 0 0 var(--primary)}
    .safety-card:focus-visible,.safety-tabs button:focus-visible,.safety-form :focus-visible{outline:3px solid color-mix(in srgb,var(--primary) 35%,transparent);outline-offset:2px}
    .safety-page :where(button,input,select,textarea,summary):focus-visible{outline:3px solid color-mix(in srgb,var(--primary) 42%,transparent);outline-offset:2px}
    .safety-card-head,.safety-actions{display:flex;align-items:center;justify-content:space-between;gap:8px;flex-wrap:wrap}
    .safety-card small{display:block;color:var(--muted);font-size:12px;line-height:1.45;margin-top:5px;overflow-wrap:anywhere}.safety-muted{color:var(--muted);font-size:12px}
    .safety-form{display:flex;flex-direction:column;gap:10px;padding:12px;border:1px solid var(--border);border-radius:10px;background:var(--card)}
    .safety-editor-focus{display:grid;gap:10px;scroll-margin-top:16px}
    .safety-form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}
    .safety-form label{display:flex;flex-direction:column;gap:4px;color:var(--muted);font-size:12px;font-weight:600}
    .safety-photo{display:block;width:100%;max-height:220px;object-fit:cover;border-radius:9px;border:1px solid var(--border)}
    .safety-photo-picker{display:grid!important;gap:8px}.safety-photo-picker>strong{color:var(--ink);font-size:14px}.safety-photo-picker small{color:var(--muted);font-size:13px;line-height:1.4}.safety-photo-picker small:not(:empty){min-height:18px}
    .safety-photo-sources,.safety-photo-preview-actions{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.safety-photo-sources label,.safety-photo-preview-actions button{align-items:center;background:var(--card);border:1px solid var(--border);border-radius:9px;color:var(--ink);cursor:pointer;display:flex;font:inherit;font-weight:700;justify-content:center;min-height:44px;padding:8px;text-align:center}.safety-photo-sources input{height:1px;opacity:0;position:absolute;width:1px}.safety-photo-sources label[aria-disabled="true"]{cursor:not-allowed;opacity:.55}.safety-photo-preview{display:grid;gap:8px}.safety-photo-preview img{border:1px solid var(--border);border-radius:10px;display:block;max-height:280px;object-fit:cover;width:100%}
    .safety-inspection-progress{display:grid;gap:7px;padding:10px;border:1px solid var(--border);border-radius:10px;background:var(--card)}.safety-inspection-progress>div{display:flex;align-items:center;justify-content:space-between;gap:8px}.safety-inspection-progress span{color:var(--muted);font-size:13px}.safety-inspection-progress progress{accent-color:var(--primary);height:8px;width:100%}.safety-inspection-progress button{min-height:44px;border:1px solid var(--border);border-radius:8px;background:var(--card);color:var(--ink);font:inherit;font-weight:700}
    .safety-registry-panel{display:grid;gap:10px}.safety-inspection-mobile{display:none}.safety-inspection-mobile-head{display:flex;justify-content:space-between;gap:8px}.safety-inspection-mobile-head button,.safety-inspection-actions button{min-height:44px;border:1px solid var(--border);border-radius:9px;background:var(--card);color:var(--ink);font:inherit;font-weight:700;padding:8px 12px}.safety-inspection-identity{align-items:start;display:flex;justify-content:space-between;gap:10px}.safety-inspection-identity h2{font-size:20px;line-height:1.35;margin:0}.safety-inspection-identity small{color:var(--muted);font-size:14px}.safety-inspection-fields{display:grid;gap:12px}.safety-inspection-fields>label,.safety-checklist-note{display:grid;gap:5px;color:var(--muted);font-size:14px;font-weight:650}.safety-inspection-fields input,.safety-inspection-fields select,.safety-inspection-fields textarea{width:100%;min-height:44px;border:1px solid var(--border);border-radius:8px;background:var(--card);color:var(--ink);padding:9px 10px;font:inherit}.safety-inspection-fields textarea{min-height:88px}.safety-checklist{display:grid;gap:10px}.safety-checklist-row{display:grid;gap:8px;margin:0;padding:10px;border:1px solid var(--border);border-radius:10px}.safety-checklist-row legend{padding:0 4px;color:var(--ink);font-size:14px;font-weight:700}.safety-checklist-choices{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:6px}.safety-checklist-choices button{min-height:44px;border:1px solid var(--border);border-radius:8px;background:var(--card);color:var(--ink);font:inherit}.safety-checklist-choices button[aria-pressed="true"]{background:var(--primary-soft);border-color:var(--primary);color:var(--primary);font-weight:800}.safety-checklist-row [role="alert"],.safety-submit-status-error{color:var(--danger)}.safety-submit-status{min-height:22px;margin:0;font-size:14px}.safety-submit-status-success{color:var(--success)}.safety-round-summary{display:grid;gap:12px;padding:14px;border:1px solid var(--border);border-radius:12px;background:var(--card)}.safety-round-summary h3{margin:0}.safety-round-summary dl{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;margin:0}.safety-round-summary dl>div{padding:10px;border-radius:9px;background:var(--primary-soft)}.safety-round-summary dt{color:var(--muted);font-size:13px}.safety-round-summary dd{margin:3px 0 0;color:var(--ink);font-size:24px;font-weight:800}.safety-round-summary button{min-height:48px;border:0;border-radius:9px;background:var(--primary);color:#fff;font:inherit;font-weight:800}
    .safety-coordinate-note{padding:8px 10px;border-radius:8px;background:var(--primary-soft);color:var(--primary);font-size:12px}
    .safety-asset-scanner{display:grid;gap:8px;padding:10px;border:1px solid var(--border);border-radius:10px;background:var(--card)}.safety-asset-scanner label{display:grid;gap:5px;color:var(--muted);font-size:13px;font-weight:700}.safety-asset-scanner input{min-height:44px;width:100%;border:1px solid var(--border);border-radius:8px;background:var(--card);color:var(--ink);padding:8px 10px;font:inherit}.safety-asset-scanner>div{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.safety-asset-scanner button{min-height:44px;border:1px solid var(--border);border-radius:8px;background:var(--card);color:var(--ink);font:inherit;font-weight:700}.safety-asset-scanner video{max-height:260px;width:100%;border-radius:9px;background:#000}.safety-asset-scanner p{margin:0;color:var(--danger);font-size:13px}.safety-draft-recovery{display:grid;gap:8px;padding:12px;border:1px solid var(--warning);border-radius:10px;background:color-mix(in srgb,var(--warning) 10%,var(--card))}.safety-draft-recovery small{color:var(--muted)}.safety-draft-recovery>div{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.safety-draft-recovery button{min-height:44px;border:1px solid var(--border);border-radius:8px;background:var(--card);color:var(--ink);font:inherit;font-weight:700}
    .lab-map-equipment[data-drag-pending="true"],.lab-map-equipment[data-dragging="true"]{touch-action:none}.lab-map-equipment[data-drag-pending="true"] .lab-map-equipment-selection-halo,.lab-map-equipment[data-dragging="true"] .lab-map-equipment-selection-halo{transform-box:fill-box;transform-origin:center;transform:scale(1.25)}.lab-map-equipment[data-dragging="true"]{filter:drop-shadow(0 4px 6px color-mix(in srgb,var(--ink) 35%,transparent))}.lab-map-safety-drag-status{min-height:20px;margin:5px 0 0;color:var(--primary);font-size:13px;font-weight:700;text-align:center}.safety-position-error{display:grid;gap:7px;margin:8px 0 0;padding:10px;border-radius:9px;background:color-mix(in srgb,var(--danger) 10%,var(--card));color:var(--danger);font-size:13px}.safety-position-error button{min-height:44px;border:1px solid var(--danger);border-radius:8px;background:var(--card);color:var(--danger);font:inherit;font-weight:700}
    .lab-map-equipment[data-draft="true"]{filter:drop-shadow(0 3px 5px color-mix(in srgb,var(--primary) 42%,transparent))}.safety-map-placement{display:grid;gap:7px;margin-top:8px;padding:12px;border:1px solid var(--primary);border-radius:10px;background:var(--primary-soft)}.safety-map-placement span,.safety-map-placement small{color:var(--muted);font-size:13px}.safety-map-placement>div{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.safety-map-placement button{min-height:44px;border:1px solid var(--border);border-radius:8px;background:var(--card);color:var(--ink);font:inherit;font-weight:700}.safety-map-placement button:last-child{background:var(--primary);border-color:var(--primary);color:#fff}.safety-advanced-coordinates{grid-column:1/-1}.safety-advanced-coordinates summary{min-height:44px;display:flex;align-items:center;color:var(--primary);cursor:pointer;font-size:13px;font-weight:700}.safety-advanced-coordinates>div{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}
    .safety-history{display:grid;gap:8px;margin-top:8px}.safety-history article{display:grid;gap:5px;padding:9px;border:1px solid var(--border);border-radius:8px}.safety-history small{color:var(--muted)}
    .safety-responsible{display:grid;gap:14px;padding:16px;border:1px solid var(--border);border-radius:12px;background:var(--card)}
    .safety-responsible-heading{display:flex;align-items:start;justify-content:space-between;gap:16px}.safety-responsible-heading p{color:var(--primary);font-size:11px;font-weight:800;letter-spacing:.1em;margin:0 0 4px}.safety-responsible-heading h2{color:var(--ink);font-size:18px;margin:0}.safety-responsible-heading>div>span{display:block;color:var(--muted);font-size:13px;line-height:1.55;margin-top:5px;max-width:720px}
    .safety-responsible-count{align-items:center;background:var(--primary-soft);border:1px solid color-mix(in srgb,var(--primary) 22%,var(--border));border-radius:10px;display:flex;flex:0 0 auto;flex-direction:column;justify-content:center;min-height:76px;min-width:116px;padding:8px}.safety-responsible-count strong{color:var(--primary);font-size:24px;line-height:1}.safety-responsible-count span{color:var(--muted);font-size:11px;margin-top:4px}
    .safety-auto-editors{display:grid;gap:10px;padding:12px;border:1px solid #b9d7eb;border-radius:10px;background:#f1f8fc}.safety-auto-editors>div{display:grid;gap:3px}.safety-auto-editors>div strong{color:#12324a;font-size:14px}.safety-auto-editors>div span{color:#476b7d;font-size:12px}.safety-auto-editors ul{display:flex;flex-wrap:wrap;gap:8px;list-style:none;margin:0;padding:0}.safety-auto-editors li{align-items:center;background:#fff;border:1px solid #d5e7f1;border-radius:9px;display:flex;gap:8px;min-height:44px;padding:7px 9px}.safety-auto-editors li>span:nth-child(2){display:grid;gap:1px;line-height:1.15}.safety-auto-editors small{color:var(--muted);font-size:11px}
    .safety-avatar{align-items:center;background:#dceff7;border-radius:50%;color:#155875;display:inline-flex;flex:0 0 auto;font-size:13px;font-weight:800;height:32px;justify-content:center;text-transform:uppercase;width:32px}.safety-editor-search{display:grid;gap:5px;color:var(--muted);font-size:12px;font-weight:700}.safety-editor-search input{min-height:44px;width:100%;border:1px solid var(--border);border-radius:8px;background:var(--card);color:var(--ink);padding:8px 10px;font:inherit}
    .safety-editor-list{display:grid;gap:7px;max-height:520px;overflow:auto}.safety-editor-list article{align-items:center;display:grid;grid-template-columns:auto minmax(0,1fr) auto auto;gap:10px;padding:10px;border:1px solid var(--border);border-radius:10px}.safety-editor-list article>div{display:grid;gap:2px;min-width:0}.safety-editor-list article strong{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.safety-editor-list article small{color:var(--muted);font-size:12px}
    .safety-mobile-switch{display:none}
    @media(max-width:767px){
      .safety-workspace{grid-template-columns:1fr}.safety-form-grid,.safety-filter-grid{grid-template-columns:1fr}.safety-responsible-heading{align-items:stretch;flex-direction:column}.safety-responsible-count{align-items:start;min-height:0}.safety-editor-list article{align-items:start;grid-template-columns:auto minmax(0,1fr)}.safety-editor-list article>span:nth-of-type(2),.safety-editor-list article button{grid-column:2}
      .safety-list{max-height:none;min-height:260px;overflow:visible}.safety-card{min-height:82px;padding:11px}.safety-card-head{align-items:start}.safety-card-head strong{line-height:1.35}.safety-card-head .badge{flex:0 0 auto}
      .safety-mobile-switch{display:flex}.safety-workspace[data-mobile-view="list"] .safety-map-pane,.safety-workspace[data-mobile-view="inspect"] .safety-map-pane{display:none}
      .safety-workspace[data-mobile-view="map"] .safety-sidebar{display:none}
      .safety-workspace[data-mobile-view="inspect"] .safety-registry-panel{display:none}.safety-workspace[data-mobile-view="inspect"] .safety-inspection-mobile{display:flex;flex-direction:column;gap:14px;min-height:calc(100dvh - 190px)}
      .safety-inspection-actions{position:sticky;bottom:0;z-index:5;display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;margin-top:auto;padding:12px 0 calc(12px + env(safe-area-inset-bottom));background:linear-gradient(transparent 0,var(--bg) 14px)}.safety-inspection-actions button{min-height:48px}.safety-inspection-actions button:last-child{grid-column:1/-1;background:var(--primary);border-color:var(--primary);color:#fff}
      .safety-inspection-fields input,.safety-inspection-fields select,.safety-inspection-fields textarea{font-size:16px}.safety-list{overscroll-behavior:auto}.safety-checklist-choices{grid-template-columns:1fr}
    }
    @media(prefers-reduced-motion:reduce){.safety-card{transition:none}.lab-map-equipment[data-drag-pending="true"] .lab-map-equipment-selection-halo{animation:none}}
  `}</style>
}
