import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'

const read = (path: string) => existsSync(path) ? readFileSync(path, 'utf8') : ''
const picker = read('components/lab-map/SafetyPhotoPicker.tsx')
const client = read('components/lab-map/SafetyAssetsClient.tsx')
const mobile = read('components/lab-map/SafetyInspectionMobile.tsx')
const styles = read('components/lab-map/SafetyAssetsStyles.tsx')
const drafts = read('lib/lab-map/safety-inspection-drafts.ts')
const scanner = read('components/lab-map/SafetyAssetScanner.tsx')

assert.match(picker, /capture="environment"/, 'camera action requests the rear camera')
assert.match(picker, /accept="image\/\*"/, 'gallery action accepts images')
assert.match(picker, /ถ่ายรูป/)
assert.match(picker, /เลือกจากคลัง/)
assert.match(picker, /URL\.createObjectURL/)
assert.match(picker, /URL\.revokeObjectURL/)
assert.match(picker, /compressSafetyPhoto/)
assert.match(picker, /uploadPercent/)
assert.match(client, /'list' \| 'map' \| 'inspect'/)
assert.match(client, /listScrollTopRef/)
assert.match(client, /SafetyInspectionProgress/)
assert.match(client, /SafetyInspectionMobile/)
assert.match(mobile, /ยืนยันและไปเครื่องถัดไป/)
assert.match(mobile, /กลับไปรายการ/)
assert.match(styles, /env\(safe-area-inset-bottom\)/)
assert.match(mobile, /uploadFileWithProgress\([\s\S]*?setUploadPercent/)
assert.match(mobile, /role=\{phase === 'error' \? 'alert' : 'status'\}/)
assert.match(mobile, /บันทึกผลตรวจแล้ว/)
assert.match(mobile, /ลองอัปโหลดอีกครั้ง/)
assert.match(client, /nextSafetyAssetCode/)
assert.match(mobile, /สรุปรอบตรวจ/)
assert.match(mobile, /ปิดรอบตรวจ/)
assert.match(drafts, /indexedDB\.open/)
assert.match(drafts, /compressedPhoto/)
assert.match(mobile, /navigator\.onLine/)
assert.match(scanner, /BarcodeDetector/)
assert.match(scanner, /กรอกรหัสอุปกรณ์/)
assert.match(styles, /--safety-touch-target:\s*44px/)
assert.match(styles, /min-height:\s*var\(--safety-touch-target\)/)
assert.match(styles, /@media\s*\(max-width:\s*767px\)/)
assert.match(styles, /@media\s*\(prefers-reduced-motion:\s*reduce\)/)
assert.doesNotMatch(styles, /\.safety-inspection-mobile[^}]*font-size:\s*(?:10|11|12)px/, 'mobile inspection body copy must be at least 14px')
assert.match(client, /roundAssetIds/, 'an active round queue must stay limited to its snapshotted assets')

console.log('lab map safety mobile flow contract passed')
