import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'
import { isProtectedPath } from '../lib/auth/session-guard'

const read = (path: string) => existsSync(path) ? readFileSync(path, 'utf8') : ''
const page = read('app/(protected)/staff/lab-map/safety-assets/page.tsx')
const safetyMapPage = read('app/(protected)/staff/lab-map/safety/page.tsx')
const client = read('components/lab-map/SafetyAssetsClient.tsx')
const photoPicker = read('components/lab-map/SafetyPhotoPicker.tsx')
const safetyMap = read('components/lab-map/SafetyEquipmentMap.tsx')
const mapPage = read('app/(protected)/staff/lab-map/page.tsx')
const staffMapClient = read('components/lab-map/LabMapStaffClient.tsx')
const mapShell = read('components/lab-map/LabMapShell.tsx')
const canvas = read('components/lab-map/LabMapCanvas.tsx')
const styles = read('components/lab-map/SafetyAssetsStyles.tsx')
const mapStyles = read('components/lab-map/LabMapStyles.tsx')
const safetyDetailDialog = read('components/lab-map/SafetyEquipmentDetailDialog.tsx')
const imageCompression = read('lib/lab-map/safety-photo-compression.ts')
const editorsApi = read('app/api/admin/lab-map/safety-editors/route.ts')
const assetsApi = read('app/api/admin/lab-map/safety-assets/route.ts')

assert.match(page, /requireSafetyViewer/)
assert.match(page, /listSafetyAssets/)
assert.match(page, /listAssemblyPoints/)
assert.match(safetyMapPage, /getStaffLabMapDTO/, 'the separate safety-equipment map reads the released map snapshot')
assert.match(safetyMap, /allowedModes=\{\['safety-assets'\]\}/, 'safety equipment has its own map mode instead of joining evacuation')
assert.match(safetyMap, /item\.kind !== 'fire-extinguisher'/, 'the equipment map excludes extinguishers reserved for evacuation maps')
assert.match(staffMapClient, /'safety-assets'/, 'the main map exposes safety equipment as a fourth tab')
assert.doesNotMatch(mapPage, /href="\/staff\/lab-map\/safety"/, 'the main map does not duplicate the safety-equipment tab as a separate primary link')
assert.match(client, /^'use client'/)
assert.match(client, /className="safety-page lab-map-shell"/, 'the safety page inherits the SVG map color tokens')
assert.match(client, /อุปกรณ์ความปลอดภัย/)
assert.match(client, /จุดรวมพล/)
assert.match(client, /navigator\.geolocation/)
assert.match(photoPicker, /capture="environment"/, 'the explicit camera action requests the rear camera')
assert.match(photoPicker, /เลือกจากคลัง/, 'a separate gallery action remains available')
assert.match(client, /Google Maps/)
assert.match(client, /คัดลอกพิกัด/)
assert.match(client, /inspection-photo/)
assert.match(client, /verification-photo/)
assert.match(client, /ผู้มีสิทธิ์อัตโนมัติ/)
assert.match(client, /ค้นหาบุคลากร/)
assert.match(client, /selectAssetFromList/, 'selecting an asset from the registry has a dedicated inspection action')
assert.doesNotMatch(client, /function selectAssetFromList\([^)]*\)\s*\{[^}]*setMobileView\('map'\)/, 'selecting an asset on a phone keeps the inspection workflow in the list view')
assert.match(client, /editorRef\.current\?\.scrollIntoView/, 'the selected inspection form is brought into view on a phone')
assert.match(client, /ดูตำแหน่งบนผัง/, 'the inspection workflow provides a direct route to the selected asset on the map')
assert.match(client, /ตำแหน่ง: \{locationLabel\}/, 'the inspection form identifies the room before a user starts checking the asset')
assert.match(photoPicker, /compressSafetyPhoto/, 'inspection and verification photos are optimized in the browser before upload')
assert.match(photoPicker, /accept="image\/\*"/, 'mobile camera and photo library are both available for evidence photos')
assert.match(canvas, /data-selected=\{selectedCode === item\.code \|\| undefined\}/, 'selected safety equipment is exposed to the SVG')
assert.match(canvas, /lab-map-equipment-selection-label/, 'the selected asset is named beside its map marker')
const mapStartPan = canvas.match(/function startPan[\s\S]*?\n  function movePan/)?.[0] ?? ''
assert.match(mapStartPan, /target\.closest\('\[data-equipment-code\]'\)/, 'pressing a safety marker must not start map panning and swallow its click')
assert.doesNotMatch(mapStartPan, /data-space-code/, 'pressing a room must remain eligible to start map panning')
assert.match(canvas, /const SAFETY_DRAG_HOLD_MS = 250/)
assert.match(canvas, /pendingSafetyDragRef/)
assert.match(canvas, /setPointerCapture/)
assert.match(canvas, /suppressSafetyClickRef/)
assert.match(canvas, /Math\.max\(0, Math\.min\(1477/)
assert.match(canvas, /document\.elementsFromPoint/)
assert.match(canvas, /closest\('\[data-space-code\]'\)/, 'room resolution must walk from the hit SVG shape to its room group')
assert.match(canvas, /onMoveSafetyEquipment\?\./)
assert.match(client, /showAllSafetyEquipment/, 'the registry map must show every safety kind even to read-only viewers')
assert.match(canvas, /draftSafetyEquipment/)
assert.match(canvas, /onMoveDraftSafetyEquipment/)
assert.match(client, /วางหมุดอุปกรณ์/)
assert.match(client, /ยืนยันตำแหน่งนี้/)
assert.match(canvas, /if \(onCoordinateSelect\) \{\s*event\.stopPropagation\(\)\s*selectCoordinate\(event\)/, 'choosing a room while adding an asset sets its coordinates instead of selecting the room')
assert.match(canvas, /item\.kind === 'fire-extinguisher'/, 'the evacuation map keeps only fire extinguishers')
assert.match(canvas, /item\.kind !== 'fire-extinguisher'/, 'non-extinguisher equipment is isolated to the safety equipment map')
assert.match(mapStyles, /\.lab-map-equipment\[data-selected\]/, 'selected safety equipment receives a visual focus treatment')
assert.match(staffMapClient, /showSafetyInspectionDetails/, 'the staff map enables inspection details for evacuation equipment')
assert.match(mapShell, /SafetyEquipmentDetailDialog/, 'clicking a safety marker opens its inspection detail dialog')
assert.match(safetyDetailDialog, /role="dialog"/, 'equipment detail is an accessible dialog')
assert.match(safetyDetailDialog, /aria-modal="true"/, 'equipment detail prevents background interaction')
assert.match(safetyDetailDialog, /latestInspection/, 'the dialog presents the latest field inspection')
assert.match(safetyDetailDialog, /photoUrl/, 'the dialog presents the latest inspection evidence photo')
assert.match(safetyDetailDialog, /Escape/, 'the dialog can be dismissed from the keyboard')
assert.match(assetsApi, /searchParams\.get\('code'\)/, 'the map loads only the selected equipment record')
assert.match(styles, /\.safety-card small\{display:block/, 'asset-card metadata has its own line and cannot overlap the next card')
assert.match(styles, /min-height:78px/, 'asset cards reserve enough height for title, status, and metadata')
assert.match(imageCompression, /MAX_SAFETY_PHOTO_DIMENSION\s*=\s*2048/, 'phone photos are downscaled to a practical maximum dimension')
assert.match(imageCompression, /canvas\.toBlob/, 'photo compression encodes a new image before upload')
assert.match(imageCompression, /image\/jpeg/, 'optimized evidence photos use the universally supported JPEG format')
assert.match(mapPage, /safety-assets/)
for (const kind of ['aed', 'first-aid-kit', 'eyewash', 'emergency-shower', 'spill-kit', 'emergency-shutoff']) {
  assert.ok(canvas.includes(`'${kind}'`) || canvas.includes(`${kind}:`), `canvas supports ${kind}`)
}
assert.match(styles, /min-height:\s*44px/)
assert.match(styles, /@media\s*\(max-width:\s*767px\)/)
assert.match(styles, /:focus-visible/)
assert.match(styles, /prefers-reduced-motion/)
assert.match(editorsApi, /normalizeRole/)
assert.match(editorsApi, /สิทธิ์อัตโนมัติ/)
assert.equal(isProtectedPath('/staff/lab-map/safety-assets'), true, 'the safety registry remains behind the staff proxy guard')
assert.equal(isProtectedPath('/staff/lab-map/safety'), true, 'the separate safety equipment map remains behind the staff proxy guard')
assert.equal(isProtectedPath('/staff/risk/map'), true, 'the risk map remains behind the staff proxy guard')

console.log('lab map safety UI contract passed')
