-- Controlled web manual metadata and per-section revision history.
-- Run manually in Supabase Dashboard -> SQL Editor. Safe to re-run.
-- For the current draft/publish workflow, run
-- scripts/manual-draft-publish-workflow.sql immediately afterwards.

alter table public.manual_sections
  add column if not exists table_data jsonb,
  add column if not exists owner_name_th text,
  add column if not exists owner_name_en text,
  add column if not exists revision_no integer not null default 1,
  add column if not exists last_change_summary text;

insert into public.manual_sections (id) values
  ('home'), ('collection'), ('transport'), ('addon'), ('report'), ('outlab'),
  ('micro'), ('bloodbank'), ('amendment')
on conflict (id) do nothing;

update public.manual_sections
set
  owner_name_th = coalesce(owner_name_th, case id
    when 'outlab' then 'งานตรวจพิเศษและปฏิบัติการตรวจต่อ'
    when 'micro' then 'งานจุลชีววิทยาคลินิก'
    when 'bloodbank' then 'งานคลังเลือด'
    else 'กลุ่มงานเทคนิคการแพทย์'
  end),
  owner_name_en = coalesce(owner_name_en, case id
    when 'outlab' then 'Special Testing and Referral Laboratory'
    when 'micro' then 'Clinical Microbiology'
    when 'bloodbank' then 'Blood Bank'
    else 'Medical Technology Department'
  end),
  last_change_summary = coalesce(last_change_summary, 'นำเข้าเนื้อหาปัจจุบันเข้าสู่คู่มือออนไลน์');

create table if not exists public.manual_publication (
  id text primary key check (id = 'main'),
  document_code text not null,
  revision text not null,
  revision_date date,
  effective_date date,
  reviewed_at date,
  approved_by_name text,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null
);

alter table public.manual_publication
  add column if not exists revised_by_name text,
  add column if not exists revision_date date;

insert into public.manual_publication (id, document_code, revision)
values ('main', 'MN-LAB-01', '13')
on conflict (id) do update set
  document_code = excluded.document_code,
  revision = excluded.revision;

create table if not exists public.manual_publication_revisions (
  id bigint generated by default as identity primary key,
  sequence_no integer not null check (sequence_no >= 0),
  revision text not null,
  revision_date date,
  effective_date date,
  change_summary text not null,
  revised_by_name text,
  approved_by_name text,
  source_document text,
  created_at timestamptz not null default now(),
  unique (sequence_no),
  unique (revision)
);

insert into public.manual_publication_revisions (
  sequence_no, revision, revision_date, effective_date, change_summary,
  revised_by_name, approved_by_name, source_document
) values
  (0, '00', null, '2007-03-16', 'ประกาศใช้ครั้งแรกทั้งฉบับ',
    'นายประกิตย์ โยธีพิทักษ์', 'นายบัณฑิต คูวิจิตรสุวรรณ',
    'Fm-QP-LAB-01/03 ประวัติการแก้ไข/ทบทวนเอกสาร (วันที่บังคับใช้ 1 มีนาคม 2568)'),
  (1, '01', '2012-02-01', '2012-03-01', 'แก้ไขทั้งฉบับ',
    'น.ส.แสงเดือน หลายวัฒนไพศาล', 'นายประกิตย์ โยธีพิทักษ์',
    'Fm-QP-LAB-01/03 ประวัติการแก้ไข/ทบทวนเอกสาร (วันที่บังคับใช้ 1 มีนาคม 2568)'),
  (2, '02', '2013-03-01', '2013-04-01', 'แก้ไขหน้า 1-5, หน้า 7, 15, 17, 35',
    'น.ส.แสงเดือน หลายวัฒนไพศาล', 'นายประกิตย์ โยธีพิทักษ์',
    'Fm-QP-LAB-01/03 ประวัติการแก้ไข/ทบทวนเอกสาร (วันที่บังคับใช้ 1 มีนาคม 2568)'),
  (3, '03', '2014-06-01', '2014-07-01', 'แก้ไขทั้งฉบับ',
    'น.ส.แสงเดือน หลายวัฒนไพศาล', 'นายประกิตย์ โยธีพิทักษ์',
    'Fm-QP-LAB-01/03 ประวัติการแก้ไข/ทบทวนเอกสาร (วันที่บังคับใช้ 1 มีนาคม 2568)'),
  (4, '04', '2015-06-01', '2015-07-01', 'แก้ไขหน้า 1-2, หน้า 5, 7-8, 12, 15, 19-20, 35, 40-50',
    'น.ส.สุขฤทัย ไพโรจน์', 'น.ส.แสงเดือน หลายวัฒนไพศาล',
    'Fm-QP-LAB-01/03 ประวัติการแก้ไข/ทบทวนเอกสาร (วันที่บังคับใช้ 1 มีนาคม 2568)'),
  (5, '05', '2016-07-01', '2016-08-01', 'แก้ไขหน้า 5, 8, 11-12, 21, 32, 35-36, 40, 47-65',
    'น.ส.สุขฤทัย ไพโรจน์', 'น.ส.แสงเดือน หลายวัฒนไพศาล',
    'Fm-QP-LAB-01/03 ประวัติการแก้ไข/ทบทวนเอกสาร (วันที่บังคับใช้ 1 มีนาคม 2568)'),
  (6, '06', '2017-09-01', '2017-10-01', 'แก้ไขทั้งฉบับ',
    'นายศิริวัฒน์ จำปีรัตน์', 'น.ส.แสงเดือน หลายวัฒนไพศาล',
    'Fm-QP-LAB-01/03 ประวัติการแก้ไข/ทบทวนเอกสาร (วันที่บังคับใช้ 1 มีนาคม 2568)'),
  (7, '07', '2019-12-01', '2020-01-01', 'แก้ไขหน้า 3-10, 12, 17-18, 21, 25-27, 32, 35, 37-39, 47-61',
    'นายศิริวัฒน์ จำปีรัตน์', 'น.ส.แสงเดือน หลายวัฒนไพศาล',
    'Fm-QP-LAB-01/03 ประวัติการแก้ไข/ทบทวนเอกสาร (วันที่บังคับใช้ 1 มีนาคม 2568)'),
  (8, '08', '2020-12-01', '2021-01-01', 'แก้ไขหน้า 4-5, 11, 45-60',
    'นายศิริวัฒน์ จำปีรัตน์', 'น.ส.วัชรี จรูญวัชร',
    'Fm-QP-LAB-01/03 ประวัติการแก้ไข/ทบทวนเอกสาร (วันที่บังคับใช้ 1 มีนาคม 2568)'),
  (9, '09', '2022-06-01', '2022-07-01', 'แก้ไขทั้งฉบับ',
    'น.ส.ณัฏฐ์ฤทัย ไพโรจน์', 'น.ส.วัชรี จรูญวัชร',
    'Fm-QP-LAB-01/03 ประวัติการแก้ไข/ทบทวนเอกสาร (วันที่บังคับใช้ 1 มีนาคม 2568)'),
  (10, '10', '2023-01-03', '2023-02-01', 'หน้า 21-23 แก้ไขค่าวิกฤติที่ต้องรายงานแพทย์ ทบทวนโดยองค์กรแพทย์และคณะอนุกรรมการมาตรฐาน IPSG 2 เมื่อวันที่ 2 พ.ย. 2565',
    'น.ส.ณัฏฐ์ฤทัย ไพโรจน์', 'น.ส.วัชรี จรูญวัชร',
    'Fm-QP-LAB-01/03 ประวัติการแก้ไข/ทบทวนเอกสาร (วันที่บังคับใช้ 1 มีนาคม 2568)'),
  (11, '11', '2023-08-01', '2024-09-01', 'แก้ไขทั้งฉบับ',
    'น.ส.ณัฏฐ์ฤทัย ไพโรจน์', 'น.ส.วัชรี จรูญวัชร',
    'Fm-QP-LAB-01/03 ประวัติการแก้ไข/ทบทวนเอกสาร (วันที่บังคับใช้ 1 มีนาคม 2568)'),
  (12, '12', '2025-02-01', '2025-03-01', 'แก้ไขทั้งฉบับ',
    'นางนฤมล งามวชิราพร', 'น.ส.ณัฏฐ์ฤทัย ไพโรจน์',
    'Fm-QP-LAB-01/03 ประวัติการแก้ไข/ทบทวนเอกสาร (วันที่บังคับใช้ 1 มีนาคม 2568)')
on conflict (revision) do update set
  sequence_no = excluded.sequence_no,
  revision_date = excluded.revision_date,
  effective_date = excluded.effective_date,
  change_summary = excluded.change_summary,
  revised_by_name = excluded.revised_by_name,
  approved_by_name = excluded.approved_by_name,
  source_document = excluded.source_document;

-- Rev. 13 represents the content currently published in the online manual.
-- Official dates and names stay null until confirmed by the document owner.
insert into public.manual_publication_revisions (
  sequence_no, revision, revision_date, effective_date, change_summary,
  revised_by_name, approved_by_name, source_document
) values (
  13, '13', null, null, 'นำเข้าเนื้อหาปัจจุบันเข้าสู่คู่มือออนไลน์',
  null, null, 'คู่มือออนไลน์ MN-LAB-01'
)
on conflict (revision) do nothing;

create table if not exists public.manual_section_revisions (
  id bigint generated by default as identity primary key,
  section_id text not null references public.manual_sections(id) on delete cascade,
  revision_no integer not null,
  change_summary text not null,
  owner_name_th text,
  owner_name_en text,
  body_html_th text not null default '',
  body_html_en text not null default '',
  table_data jsonb,
  changed_at timestamptz not null default now(),
  changed_by uuid references auth.users(id) on delete set null,
  changed_by_name text,
  unique (section_id, revision_no)
);

create index if not exists idx_manual_section_revisions_section_changed
  on public.manual_section_revisions(section_id, changed_at desc);

alter table public.manual_publication enable row level security;
alter table public.manual_publication_revisions enable row level security;
alter table public.manual_section_revisions enable row level security;

drop policy if exists "manual_publication_public_read" on public.manual_publication;
create policy "manual_publication_public_read"
  on public.manual_publication for select to anon, authenticated using (true);

drop policy if exists "manual_publication_auth_write" on public.manual_publication;

drop policy if exists "manual_publication_revisions_public_read" on public.manual_publication_revisions;
create policy "manual_publication_revisions_public_read"
  on public.manual_publication_revisions for select to anon, authenticated using (true);

drop policy if exists "manual_publication_revisions_auth_write" on public.manual_publication_revisions;

drop policy if exists "manual_revisions_public_read" on public.manual_section_revisions;
create policy "manual_revisions_public_read"
  on public.manual_section_revisions for select to anon, authenticated using (true);

drop policy if exists "manual_revisions_auth_write" on public.manual_section_revisions;

grant select on table
  public.manual_publication,
  public.manual_publication_revisions,
  public.manual_section_revisions
to anon, authenticated;

revoke insert, update, delete on table
  public.manual_publication,
  public.manual_publication_revisions,
  public.manual_section_revisions
from anon, authenticated;

grant select, insert, update, delete on table
  public.manual_publication,
  public.manual_publication_revisions,
  public.manual_section_revisions
to service_role;

grant usage, select on sequence
  public.manual_publication_revisions_id_seq,
  public.manual_section_revisions_id_seq
to service_role;

-- Keep the document-control fields in the row for the current manual revision.
-- This is deliberately separate from section history: changing a section never
-- increases the document revision number.
create or replace function public.sync_manual_publication_revision_history()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  update public.manual_publication_revisions history
  set
    revision_date = new.revision_date,
    effective_date = new.effective_date,
    revised_by_name = new.revised_by_name,
    approved_by_name = new.approved_by_name
  where history.revision = new.revision;

  return new;
end;
$$;

drop trigger if exists trg_manual_publication_revision_sync on public.manual_publication;
create trigger trg_manual_publication_revision_sync
after insert or update of revision, revision_date, effective_date, revised_by_name, approved_by_name
on public.manual_publication
for each row execute function public.sync_manual_publication_revision_history();

create or replace function public.bump_manual_section_revision()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  if row(new.body_html_th, new.body_html_en, new.table_data, new.owner_name_th, new.owner_name_en)
     is not distinct from
     row(old.body_html_th, old.body_html_en, old.table_data, old.owner_name_th, old.owner_name_en) then
    new.revision_no := old.revision_no;
  else
    new.revision_no := old.revision_no + 1;
  end if;

  return new;
end;
$$;

create or replace function public.capture_manual_section_revision()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
declare
  actor_name text;
begin
  if tg_op = 'UPDATE' and new.revision_no = old.revision_no then
    return new;
  end if;

  select p.name into actor_name from public.profiles p where p.id = new.updated_by;

  insert into public.manual_section_revisions (
    section_id, revision_no, change_summary,
    owner_name_th, owner_name_en, body_html_th, body_html_en, table_data,
    changed_at, changed_by, changed_by_name
  ) values (
    new.id, new.revision_no,
    coalesce(nullif(btrim(new.last_change_summary), ''), 'ปรับปรุงเนื้อหาคู่มือออนไลน์'),
    new.owner_name_th, new.owner_name_en, new.body_html_th, new.body_html_en, new.table_data,
    coalesce(new.updated_at, now()), new.updated_by, actor_name
  )
  on conflict (section_id, revision_no) do nothing;

  -- A content edit updates the online-manual review date and records its
  -- summary in the current document revision without changing Rev. number.
  update public.manual_publication publication
  set
    reviewed_at = (
      select max(section.updated_at)::date
      from public.manual_sections section
    ),
    revised_by_name = coalesce(actor_name, publication.revised_by_name)
  where publication.id = 'main';

  update public.manual_publication_revisions history
  set
    revision_date = coalesce(new.updated_at, now())::date,
    effective_date = publication.effective_date,
    change_summary = coalesce(nullif(btrim(new.last_change_summary), ''), 'ปรับปรุงเนื้อหาคู่มือออนไลน์'),
    revised_by_name = coalesce(actor_name, publication.revised_by_name),
    approved_by_name = publication.approved_by_name,
    source_document = 'คู่มือออนไลน์ MN-LAB-01'
  from public.manual_publication publication
  where publication.id = 'main'
    and history.revision = publication.revision;

  return new;
end;
$$;

drop trigger if exists trg_manual_section_revision on public.manual_sections;
create trigger trg_manual_section_revision
before update on public.manual_sections
for each row execute function public.bump_manual_section_revision();

drop trigger if exists trg_manual_section_revision_capture on public.manual_sections;
create trigger trg_manual_section_revision_capture
after insert or update on public.manual_sections
for each row execute function public.capture_manual_section_revision();

insert into public.manual_section_revisions (
  section_id, revision_no, change_summary,
  owner_name_th, owner_name_en, body_html_th, body_html_en, table_data,
  changed_at, changed_by, changed_by_name
)
select
  section.id, section.revision_no,
  coalesce(section.last_change_summary, 'นำเข้าเนื้อหาปัจจุบันเข้าสู่คู่มือออนไลน์'),
  section.owner_name_th, section.owner_name_en,
  section.body_html_th, section.body_html_en, section.table_data,
  section.updated_at, section.updated_by, profile.name
from public.manual_sections section
left join public.profiles profile on profile.id = section.updated_by
on conflict (section_id, revision_no) do nothing;

update public.manual_publication
set reviewed_at = (
  select max(section.updated_at)::date
  from public.manual_sections section
)
where id = 'main';

-- Backfill the current online-manual row so the initial Rev. 13 display uses
-- the same effective date, latest review date, reviser, and approver as the
-- document-control card. Its original import summary is retained until the
-- next documented section edit supplies a new summary.
update public.manual_publication_revisions history
set
  revision_date = publication.reviewed_at,
  effective_date = publication.effective_date,
  revised_by_name = publication.revised_by_name,
  approved_by_name = publication.approved_by_name,
  source_document = 'คู่มือออนไลน์ MN-LAB-01'
from public.manual_publication publication
where publication.id = 'main'
  and history.revision = publication.revision;
