import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const sql = readFileSync('scripts/manual-web-source-of-truth.sql', 'utf8')
const draftWorkflow = readFileSync('scripts/manual-draft-publish-workflow.sql', 'utf8')
const reviewOnlyWorkflow = readFileSync('scripts/manual-section-review-only.sql', 'utf8')
const revisionDateWorkflow = readFileSync('scripts/manual-document-revision-date.sql', 'utf8')
const reviewOnlyTrigger = reviewOnlyWorkflow.split('$$;')[0] ?? reviewOnlyWorkflow
const route = readFileSync('app/api/admin/manual/[id]/route.ts', 'utf8')
const publishRoute = readFileSync('app/api/admin/manual/[id]/publish/route.ts', 'utf8')
const settings = readFileSync('app/api/admin/manual/settings/route.ts', 'utf8')
const shell = readFileSync('app/(public)/manual/ManualShell.tsx', 'utf8')
const page = readFileSync('app/(public)/manual/page.tsx', 'utf8')
const governance = readFileSync('app/(public)/manual/ManualGovernance.tsx', 'utf8')

assert.match(sql, /create table if not exists public\.manual_publication/i)
assert.match(sql, /add column if not exists revised_by_name text/i)
assert.match(sql, /add column if not exists revision_date date/i)
assert.match(sql, /create table if not exists public\.manual_publication_revisions/i)
assert.match(sql, /create table if not exists public\.manual_section_revisions/i)
assert.match(sql, /capture_manual_section_revision/i)
assert.match(sql, /sync_manual_publication_revision_history/i)
assert.match(sql, /trg_manual_publication_revision_sync/i)
assert.match(sql, /set reviewed_at = \([\s\S]*max\(section\.updated_at\)::date/i)
assert.match(sql, /revision_date = coalesce\(new\.updated_at, now\(\)\)::date/i)
assert.match(sql, /revision_date = publication\.reviewed_at/i)
assert.match(sql, /unique \(section_id, revision_no\)/i)
assert.match(sql, /\('micro'\), \('bloodbank'\), \('amendment'\)/i)
assert.match(sql, /\(11, '11', '2023-08-01', '2024-09-01', 'แก้ไขทั้งฉบับ'/)
assert.match(sql, /\(12, '12', '2025-02-01', '2025-03-01', 'แก้ไขทั้งฉบับ'/)
assert.match(sql, /13, '13', null, null, 'นำเข้าเนื้อหาปัจจุบันเข้าสู่คู่มือออนไลน์'/)
assert.match(sql, /revoke insert, update, delete on table[\s\S]*from anon, authenticated/i)
assert.doesNotMatch(sql, /auth\.role\(\)/i)
assert.match(route, /manualSectionPatchSchema/)
assert.match(route, /manual_section_revisions/)
assert.match(route, /manual_section_drafts/)
assert.match(draftWorkflow, /create table if not exists public\.manual_section_drafts/i)
assert.match(draftWorkflow, /publish_manual_section_draft/i)
assert.match(draftWorkflow, /app\.manual_publish/i)
assert.match(draftWorkflow, /section_id = 'micro' and revision_no >= 2/i)
assert.match(reviewOnlyWorkflow, /set reviewed_at = \(select max\(section\.updated_at\)::date/i)
assert.doesNotMatch(reviewOnlyTrigger, /update public\.manual_publication_revisions/i)
assert.doesNotMatch(reviewOnlyTrigger, /revised_by_name/i)
assert.match(revisionDateWorkflow, /revision_date = new\.revision_date/i)
assert.match(revisionDateWorkflow, /update of revision, revision_date, effective_date/i)
assert.match(publishRoute, /publish_manual_section_draft/)
assert.match(settings, /\['Admin', 'Manager'\]/)
assert.match(settings, /revised_by_name/)
assert.match(settings, /revision_date/)
assert.match(settings, /reviewed_at: _ignoredReviewedAt/)
assert.doesNotMatch(settings, /from\('manual_publication_revisions'\)/)
assert.match(shell, /ManualDocumentControl/)
assert.match(shell, /publicationHistory/)
assert.match(shell, /ManualSectionGovernance/)
assert.match(page, /latestSectionUpdatedAt/)
assert.match(governance, /ทบทวนล่าสุด \(อัตโนมัติ\)/)
assert.doesNotMatch(governance, /name="reviewed_at"/)

console.log('scripts/manual-web-source-of-truth.test.ts: all assertions passed')
