import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'

const read = (path: string) => readFileSync(join(process.cwd(), path), 'utf8')
const resources = read('lib/permission-resources.ts')
const sidebar = read('components/layout/StaffSidebar.tsx')
const topbar = read('components/layout/StaffTopbar.tsx')
const dashboard = read('components/quality-tasks/QualityTaskDashboard.tsx')
const css = read('app/globals.css')
const dialog = read('components/quality-tasks/QualityTaskDialog.tsx')
const registry = read('components/quality-tasks/QualityTaskRegistry.tsx')
const checkIn = read('components/quality-tasks/QualityTaskCheckInClient.tsx')
const guestCheckIn = read('components/quality-tasks/QualityTaskGuestCheckInClient.tsx')
const qualityServer = read('lib/quality-tasks/server.ts')
const staffDashboard = read('app/(protected)/staff/dashboard/page.tsx')
const occurrenceRoute = read('app/api/admin/quality-tasks/occurrences/[id]/route.ts')
const completionNoteMigration = read('supabase/migrations/20260901101806_quality_task_completion_note_metadata.sql')
const meetingOverlapMigration = read('supabase/migrations/20260901113000_quality_task_meeting_overlap_guard.sql')
const attachmentRoute = read('app/api/admin/quality-tasks/attachments/[id]/route.ts')
const permissionSeed = read('scripts/seed-role-permissions.sql')
const icons = read('components/ui/Icon.tsx')
const actionItemsRoute = read('app/api/admin/quality-tasks/occurrences/[id]/action-items/route.ts')
const actionItemRoute = read('app/api/admin/quality-tasks/occurrences/[id]/action-items/[itemId]/route.ts')

assert.ok(resources.includes("'งานคุณภาพ'"), 'permission resource is registered')
assert.ok(sidebar.includes("href: '/staff/quality-tasks'"), 'sidebar links to quality tasks')
assert.ok(sidebar.includes("'/staff/quality-tasks/registry'"), 'sidebar links to registry')
assert.ok(topbar.includes("'/staff/quality-tasks':     { th: 'งานคุณภาพ'"), 'topbar names the quality tasks module')
assert.ok(topbar.includes("'/staff/quality-tasks/registry': { th: 'ทะเบียนกิจกรรมคุณภาพ'"), 'topbar names the quality task registry')
assert.ok(dashboard.includes('qt-calendar'), 'module renders a responsive monthly calendar')
assert.ok(dashboard.includes('งานของฉัน'), 'module provides My Tasks scope')
assert.ok(dashboard.includes('attachments/presign') && dashboard.includes('attachments/finalize'), 'dashboard uses direct R2 upload flow')
assert.ok(qualityServer.includes('assertNoMeetingConflict') && qualityServer.includes('ช่วงเวลาดังกล่าวมีประชุมแล้ว'), 'ad-hoc meetings reject overlapping time slots')
assert.ok(qualityServer.includes('excludeInstanceId') && qualityServer.includes('occurrenceCalendarRange'), 'rescheduling meetings checks conflicts without colliding with itself')
assert.ok(dashboard.includes('meetingSlotsOverlap') && dashboard.includes('isSelectedMeetingPresetOccupied') && dashboard.includes('มีประชุมแล้ว'), 'meeting time presets show occupied slots and prevent accidental selection')
assert.ok(meetingOverlapMigration.includes('pg_advisory_xact_lock') && meetingOverlapMigration.includes('guard_quality_task_meeting_slot'), 'database serializes and rejects concurrent overlapping meeting saves')
assert.ok(staffDashboard.includes('qualityUrgent') && staffDashboard.includes('/staff/quality-tasks'), 'staff dashboard links urgent quality tasks')
assert.ok(occurrenceRoute.includes("z.literal('complete')") && occurrenceRoute.includes("z.literal('reopen')"), 'occurrence API exposes guarded workflow actions')
assert.ok(occurrenceRoute.includes("z.literal('save_completion_note')"), 'occurrence API exposes a separate meeting-summary save action')
assert.ok(qualityServer.includes('completion_note_updated_by') && qualityServer.includes('completion_note_updated_at'), 'server persists meeting-summary save metadata')
assert.ok(dashboard.includes('บันทึกสรุปมติ') && dashboard.includes('fmtSavedAt') && dashboard.includes('personName'), 'meeting summary shows a save button and saved-by status')
assert.ok(completionNoteMigration.includes('ADD COLUMN IF NOT EXISTS completion_note_updated_by') && completionNoteMigration.includes('ADD COLUMN IF NOT EXISTS completion_note_updated_at'), 'migration adds dedicated meeting-summary metadata columns')
assert.ok(permissionSeed.includes("('Manager', 'งานคุณภาพ:edit'"), 'role reset seed preserves manager edit access')
assert.ok(permissionSeed.includes("('Assistant', 'งานคุณภาพ:view'"), 'role reset seed preserves viewer access')
assert.ok(icons.includes('calendar:'), 'quality-task navigation has a real calendar icon')
assert.ok(dashboard.includes('ผู้รับผิดชอบทุกคน') && dashboard.includes('ทุกทีม'), 'dashboard exposes explicit assignee and team filters')
assert.ok(dashboard.includes('/history'), 'detail card loads audit history')
assert.match(dashboard, /method:\s*["']DELETE["']/, 'edit users can delete eligible evidence from the detail card')
assert.match(dashboard, /mode:\s*["']adHoc["']/, 'edit users can create occurrences from manual templates')
assert.ok(dashboard.includes('สถานที่/ช่องทาง'), 'ad-hoc meeting form captures the location or meeting channel')
assert.ok(dashboard.includes('ผู้เข้าร่วม'), 'ad-hoc meeting form exposes participant selection')
assert.ok(dashboard.includes('วัตถุประสงค์/วาระ'), 'ad-hoc meeting form captures the meeting agenda')
assert.ok(dashboard.includes('PdfViewerModal') && dashboard.includes('proxy=1'), 'quality-task evidence opens in the in-page PDF reader')
assert.ok(attachmentRoute.includes('r2ObjectResponse') && attachmentRoute.includes("searchParams.get('proxy')"), 'quality-task evidence supports an authenticated inline proxy')
assert.ok(dashboard.includes('ACTION ITEMS'), 'meeting detail card shows an action items section')
assert.ok(dashboard.includes('action-items'), 'dashboard calls the action items API')
assert.ok(actionItemsRoute.includes('qualityTaskContext') && actionItemRoute.includes('qualityTaskContext'), 'action item routes go through the shared quality-task auth context')
assert.ok(actionItemsRoute.includes('listActionItems') && actionItemsRoute.includes('createActionItem'), 'action items collection route lists and creates')
assert.ok(actionItemRoute.includes('updateActionItem') && actionItemRoute.includes('deleteActionItem'), 'action item item route updates and deletes')


// การประชุม vs กิจกรรม ต้องแยกกันได้โดยไม่พึ่งสี — พื้นการ์ด, สไตล์แถบซ้าย และไอคอนนำ ต้องคงอยู่ครบ
assert.ok(dashboard.includes('qt-card-meeting') && dashboard.includes('qt-card-activity'), 'calendar cards carry a task-kind class')
assert.ok(dashboard.includes('border-left-style:dashed'), 'activity cards differ from meetings by border style, not colour alone')
assert.match(dashboard, /TASK_KIND_META[\s\S]{0,240}?meeting:[\s\S]{0,120}?icon: "users"/, 'meeting cards keep a distinct leading glyph')
assert.match(dashboard, /TASK_KIND_META[\s\S]{0,240}?activity:[\s\S]{0,120}?icon: "clipboard"/, 'activity cards carry their own leading glyph')
assert.ok(dashboard.includes('qt-kind-legend'), 'calendar explains its two card kinds with a legend')
assert.ok(dashboard.includes('occurrenceCalendarRange'), 'calendar derives a safe visible range after rescheduling')
assert.match(dashboard, /selected\.scheduleId === null[\s\S]{0,260}occurrenceCalendarRange\(selected\)/, 'ad-hoc appointment details use the moved calendar date')
assert.ok(qualityServer.includes('planned_date.gte.${input.from}') && qualityServer.includes('planned_date.lte.${input.to}'), 'occurrence query includes explicitly moved dates')

// รายการด้านล่างปฏิทิน: เข้าถึงด้วยคีย์บอร์ดได้ เรียงลำดับได้ และไม่เรียกงานทุกชนิดว่า "กิจกรรม"
assert.ok(dashboard.includes('งานทั้งหมด ('), 'list heading covers both task kinds, not just activities')
assert.ok(!dashboard.includes('กิจกรรมทั้งหมด'), 'list heading no longer collides with the activity task kind')
assert.ok(dashboard.includes('qt-row-btn'), 'table rows are reachable through a real button, not a bare clickable <tr>')
assert.ok(dashboard.includes('aria-sort'), 'sortable columns announce their sort state')
assert.ok(dashboard.includes('LIST_COLUMNS') && dashboard.includes('URGENCY_ORDER'), 'list columns and status ordering live in one place')
assert.ok(!dashboard.includes('#0E7490'), 'list cells use design tokens instead of hardcoded hex')

// Shared dialog guardrails: every Quality Tasks modal gets one close affordance
// and the same keyboard semantics, including the nested participant picker.
assert.equal((dashboard.match(/<QualityTaskDialog/g) ?? []).length, 5, 'dashboard modals use the shared dialog')
assert.equal((registry.match(/<QualityTaskDialog/g) ?? []).length, 2, 'registry modals use the shared dialog')
assert.ok(dialog.includes('role="dialog"') && dialog.includes('aria-modal="true"'), 'shared dialog exposes modal semantics')
assert.ok(dialog.includes('quality-task-dialog-body') && dialog.includes('overflow: "hidden"'), 'dialog keeps the close control outside the scrolling body')
assert.ok(dialog.includes('body.style.overflow = "hidden"') && dialog.includes('onWheelCapture') && dialog.includes('onTouchMoveCapture') && dialog.includes('event.preventDefault()'), 'dialog locks background scrolling and blocks outside-wheel chaining')
assert.ok(css.includes('scrollbar-gutter: stable') && css.includes('scrollbar-width: none') && css.includes('.quality-task-dialog-body::-webkit-scrollbar { display: none; }'), 'dialog scrolls without a persistent rail under the close control')
assert.ok(css.includes('.quality-task-dialog-close {') && css.includes('border: 1px solid var(--danger);') && css.includes('color: var(--danger);') && css.includes('background: var(--card);'), 'every shared dialog close control is visibly red and opaque')
assert.ok(dashboard.includes('const closeStyle: React.CSSProperties') && dashboard.includes('background: "color-mix(in srgb, var(--danger) 8%, var(--card))"') && dashboard.includes('color: "var(--danger)"'), 'inline Quality Tasks remove controls keep the same red cross treatment')
assert.ok(dialog.includes('event.key === "Escape"') && dialog.includes('event.key !== "Tab"'), 'shared dialog supports Escape and Tab handling')
assert.ok(dialog.includes('dialogs[dialogs.length - 1] !== panel'), 'nested dialogs only handle keyboard events at the top level')
assert.ok(dialog.includes('openerRef.current?.isConnected'), 'shared dialog restores focus to its opener')
assert.ok(dashboard.includes('closeTone="danger"') && dashboard.includes('quality-task-qr-title'), 'QR dialog keeps a prominent danger close affordance')
assert.ok(!dashboard.includes('quality-task-qr-modal-close'), 'QR dialog no longer depends on the legacy close class')
assert.ok(dashboard.includes('state === "unscheduled"') && dashboard.includes('value="normal"'), 'task filters expose unscheduled and normal work')
assert.ok(dashboard.includes('function clearFilters()') && dashboard.includes('ล้างตัวกรอง'), 'active filters can be cleared explicitly')
assert.ok(dashboard.includes('ไม่พบงานตามตัวกรอง') && dashboard.includes('ยังไม่มีงานในเดือนนี้'), 'empty states distinguish no data from no filter matches')
assert.ok(dashboard.includes('className="qt-summary-grid"') && dashboard.includes('className="qt-action-item-form"'), 'dashboard uses responsive layout hooks')
assert.ok(css.includes('.qt-filter-bar') && css.includes('.quality-task-dialog-panel'), 'quality task responsive rules are centralized')
assert.ok(dashboard.includes('aria-label="กรองตามสถานะและกำหนดส่ง"') && dashboard.includes('aria-live="assertive"'), 'dashboard filters and errors have accessible announcements')
assert.ok(dashboard.includes('aria-expanded={disabled ? undefined : isExpanded}') && dashboard.includes('type="button"'), 'participant groups use native keyboard controls')
assert.ok(guestCheckIn.includes('role="alert"') && checkIn.includes('role="alert"'), 'check-in error states are announced')
assert.ok(dashboard.includes('statusText') && dashboard.includes('สถานะ ${statusText[o.status]}'), 'task lifecycle status is visible alongside urgency')
assert.ok(dashboard.includes('selectedCanComplete') && dashboard.includes('ต้องแนบ PDF หลักฐานก่อนกด'), 'completion keeps the manual action and explains missing evidence')
assert.ok(registry.includes('qt-registry-form-grid') && registry.includes('qt-registry-schedule-row') && registry.includes('qt-registry-assignee-row'), 'registry forms expose responsive layout hooks')
assert.ok(registry.includes('aria-label="ค้นหาทะเบียนกิจกรรมคุณภาพ"') && registry.includes('qt-registry-clear-filter'), 'registry filters are labelled and resettable')
assert.ok(registry.includes('aria-expanded={disabled ? undefined : isExpanded}') && registry.includes('ariaLabel={`${group.label} ทั้งหมด`}'), 'registry participant groups use native keyboard controls')
assert.ok(registry.includes('filtered.length === 0') && registry.includes('ไม่พบรายการตามตัวกรอง'), 'registry has a useful empty state')

console.log('scripts/quality-task-ui.test.ts: all assertions passed')
