import assert from 'node:assert/strict'
import fs from 'node:fs'

const read = (path: string) => fs.readFileSync(path, 'utf8')
const checkInSql = read('scripts/quality-task-check-in.sql')
const checkInLogic = read('lib/quality-tasks/check-in.ts')
const checkInWindow = read('lib/quality-tasks/check-in-window.ts')
const adminRoute = read('app/api/admin/quality-tasks/occurrences/[id]/check-in-token/route.ts')
const dashboard = read('components/quality-tasks/QualityTaskDashboard.tsx')
const client = read('components/quality-tasks/QualityTaskCheckInClient.tsx')
const guestClient = read('components/quality-tasks/QualityTaskGuestCheckInClient.tsx')

assert.match(checkInSql, /check_in_closed_at/, 'schema must store a manual check-in close timestamp')
assert.match(checkInSql, /check_in_opened_at/, 'schema must store an early check-in opening timestamp')
assert.match(checkInLogic, /closeCheckIn/, 'server logic must expose a close operation')
assert.match(checkInLogic, /openCheckIn/, 'server logic must expose an early opening operation')
assert.match(checkInLogic, /check_in_closed_at/, 'check-in reads must enforce the close timestamp')
assert.match(checkInLogic, /not_open/, 'check-in writes must enforce the opening window')
assert.match(checkInWindow, /CHECK_IN_EARLY_MINUTES = 60/, 'check-in window opens one hour early')
assert.match(checkInLogic, /title:\s*occurrenceDisplayTitle\(/, 'QR check-in context must use the occurrence subject/title, not only the template')
assert.match(dashboard, /\{adHocIsMeeting \? "ชื่อประชุม" : "ชื่อรอบ\/เหตุการณ์"\}/, 'ad-hoc meeting form must label the occurrence subject as the meeting name')
assert.ok(dashboard.includes('ชื่อนี้จะแสดงบนหน้า QR เช็คอิน'), 'ad-hoc meeting form must explain where the meeting name is shown')
assert.match(adminRoute, /export async function PATCH/, 'admin route must expose a close endpoint')
assert.match(adminRoute, /export async function PUT/, 'admin route must expose an early opening endpoint')
assert.match(dashboard, /ปิดรับ Check-in/, 'QR modal must offer a close check-in button')
assert.match(dashboard, /เปิดรับ Check-in ตอนนี้/, 'QR modal must offer an early opening button')
assert.match(client, /ปิดรับเช็คอินแล้ว/, 'check-in page must explain the manual close state')
assert.match(client, /notOpenYet/, 'logged-in check-in page must explain the scheduled opening state')
assert.match(guestClient, /notOpenYet/, 'guest check-in page must explain the scheduled opening state')

console.log('scripts/quality-task-check-in.test.ts: all assertions passed')
