import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'

const read = (path: string) => readFileSync(join(process.cwd(), path), 'utf8')
const hub = read('components/safety-tasks/SafetyTaskHub.tsx')
const safetyServer = read('lib/quality-tasks/safety-server.ts')

assert.match(hub, /function groupSafetyEvidence\(/, 'annual evidence defines a grouping helper')
assert.match(hub, /safety-evidence-groups/, 'annual evidence renders grouped sections')
assert.match(hub, /aria-expanded=\{!collapsed\}/, 'evidence groups expose collapse state accessibly')
assert.match(hub, /safety-evidence-group-toggle/, 'evidence groups have an explicit expand/collapse control')
assert.match(hub, /useState<Record<string, boolean>>\(\(\) => Object\.fromEntries/, 'evidence groups start compact with only the latest group expanded')
assert.match(hub, /safety-evidence-preview/, 'image evidence renders an in-page preview trigger')
assert.match(hub, /safety-evidence-lightbox/, 'image evidence renders an in-page popup viewer')
assert.match(hub, /role="dialog" aria-modal="true"/, 'image popup exposes dialog semantics')
assert.match(hub, /setEvidencePreview\(null\)/, 'image popup can be closed')
assert.match(hub, /loading="lazy"/, 'evidence thumbnails load lazily')
assert.match(hub, /function filterSafetyEvidence\(/, 'annual evidence filters items through a dedicated search helper')
assert.match(hub, /useDeferredValue/, 'annual evidence search defers filtering while typing')
assert.match(hub, /safety-evidence-search/, 'annual evidence exposes a dedicated search field')
assert.match(hub, /safety-evidence-subgroups/, 'annual evidence renders nested item groups')
assert.match(hub, /assetKind/, 'inspection evidence carries the equipment kind for top-level grouping')
assert.match(hub, /assetCode/, 'inspection evidence carries the equipment code for item grouping')
assert.match(hub, /Intl\.Collator\('th', \{ numeric: true/, 'nested equipment groups use natural numeric sorting')
assert.match(hub, /sortNumber/, 'nested equipment groups retain a numeric sort key')
assert.match(hub, /ไม่พบหลักฐาน/, 'annual evidence explains when a search has no results')
assert.match(hub, /function linkedTaskForEvidence\(/, 'annual evidence resolves linked tasks through a dedicated helper')
assert.match(hub, /if \(file\.instanceId\) return occurrences\.find\(item => item\.instanceId === file\.instanceId\)/, 'linked inspection evidence resolves by instance id before any fallback')
assert.match(hub, /file\.sourceKind !== 'inspection' \|\| !file\.taskSourceKey \|\| !file\.inspectedOn/, 'unlinked evidence without a safe task key stays unlinked')
assert.match(hub, /file\.taskSourceKey/, 'inspection evidence carries the source key needed to resolve its safety task')
assert.match(hub, /file\.inspectedOn/, 'inspection evidence carries the inspection date needed to resolve its safety task period')
assert.match(hub, /template\.sourceKey === file\.taskSourceKey/, 'unlinked inspection evidence resolves to the matching safety task family')
assert.match(hub, /selectedInspectionEvidence/, 'task drawer derives inspection evidence for the selected safety task')
assert.match(hub, /รูปตรวจอุปกรณ์จาก Inspection Round/, 'task drawer labels inspection evidence separately from uploaded attachments')
assert.match(hub, /inspectionEvidence\.assetCount/, 'task drawer shows the number of inspected equipment points')
assert.match(safetyServer, /taskSourceKey: inspectionSourceKeyForAssetKind/, 'inspection evidence exposes its matching safety task family')
assert.match(safetyServer, /select\('id,name_th,code,kind'\)/, 'annual evidence loads equipment metadata for grouping')
assert.match(safetyServer, /assetKind, assetCode: nullable\(asset\?\.code\)/, 'annual evidence returns equipment kind metadata')
assert.match(safetyServer, /function latestInspectionEvidenceRows\(/, 'annual evidence defines a latest-photo-per-equipment selector')
assert.match(safetyServer, /const inspections = latestInspectionEvidenceRows\(\(inspectionRows/, 'annual evidence uses one latest inspection photo per equipment')

console.log('scripts/safety-evidence-ui.test.ts: all assertions passed')
