import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const read = (path: string) => readFileSync(resolve(process.cwd(), path), 'utf8')
const css = read('app/globals.css')
const primitives = read('components/satisfaction/SatisfactionPrimitives.tsx')
const dialog = read('components/satisfaction/SatisfactionDialog.tsx')
const module = read('components/satisfaction/SatisfactionModule.tsx')
const exports = read('components/satisfaction/SatisfactionExportActions.tsx')
const dashboard = read('components/satisfaction/SatisfactionDashboard.tsx')
const charts = read('components/satisfaction/SatisfactionCharts.tsx')
const campaigns = read('components/satisfaction/CampaignManager.tsx')
const comments = read('components/satisfaction/SurveyComments.tsx')
const editors = read('components/satisfaction/SatisfactionEditors.tsx')

assert.match(css, /\.satisfaction-module(?:,\s*\.satisfaction-builder-page)?\s*\{/, 'shared satisfaction styles are scoped to the module')
assert.match(css, /\.satisfaction-builder-page\s*\{/, 'builder receives a shared visual root')
assert.match(css, /prefers-reduced-motion:\s*reduce/, 'satisfaction motion has a reduced-motion path')
assert.match(primitives, /export function SatisfactionStatusBadge/, 'status badge is shared')
assert.match(primitives, /export function SatisfactionSummaryCard/, 'summary card is shared')
assert.match(primitives, /aria-live="polite"/, 'shared async state is announced')
assert.match(dialog, /aria-modal="true"/, 'dialog is modal')
assert.match(dialog, /Escape/, 'dialog supports Escape close')
assert.match(module, /className="satisfaction-module satisfaction-page"/, 'staff module uses the scoped root')
assert.match(module, /SatisfactionSummaryCard/, 'overview uses the shared KPI primitive')
assert.match(module, /className="satisfaction-summary-grid"/, 'overview groups KPIs in one responsive grid')
assert.match(module, /data-label="ชื่อแบบสำรวจ \/ รหัส"/, 'survey rows have mobile labels')
assert.match(module, /<caption className="satisfaction-visually-hidden"/, 'survey and campaign tables have accessible captions')
assert.match(exports, /className="satisfaction-overview-actions"/, 'report actions have a named surface')
assert.match(exports, /aria-live="polite"/, 'report actions announce completion/error state')
assert.match(dashboard, /SatisfactionInlineError/, 'dashboard errors use the shared retry surface')
assert.match(dashboard, /onRetry=\{\(\) => void load\(\)\}/, 'dashboard errors offer retry')
assert.match(dashboard, /aria-live="polite"/, 'dashboard refresh state is announced')
assert.match(dashboard, /lastUpdated/, 'dashboard exposes a last-updated state')
assert.match(charts, /responseCount === 0/, 'charts have an explicit no-data branch')
assert.match(charts, /satisfaction-chart-table/, 'chart tables use a shared accessible class')
assert.match(campaigns, /useRouter/, 'campaign mutations refresh without a full browser reload')
assert.match(campaigns, /aria-live="polite"/, 'campaign mutation feedback is announced')
assert.match(campaigns, /copyState/, 'QR copy has explicit success state')
assert.match(campaigns, /SatisfactionDialog/, 'QR uses the shared accessible dialog')
assert.match(campaigns, /aria-busy/, 'busy campaign controls expose mutation state')
assert.match(comments, /markBusyId/, 'comment mutations track the individual busy row')
assert.match(comments, /aria-busy/, 'comment mutation exposes busy state')
assert.match(comments, /ผลการค้นหา/, 'comments expose result context')
assert.match(comments, /SatisfactionLoadingState/, 'comments use a structured loading state')
assert.match(editors, /SatisfactionInlineError/, 'settings load errors use the shared retry surface')
assert.match(editors, /onRetry=\{\(\) => void loadEditors\(\)\}/, 'settings load errors offer retry')
assert.match(editors, /toggleBusyId/, 'settings toggles expose busy state')

console.log('satisfaction shared UI contract tests passed')
