import { z } from 'zod'

export const testSchema = z.object({
  code:                z.string().min(1, 'กรุณากรอกรหัสรายการตรวจ'),
  lis_code:            z.string().nullish(),
  category_id:         z.string().min(1, 'กรุณาเลือกหมวดหมู่'),
  th:                  z.string().min(1, 'กรุณากรอกชื่อภาษาไทย'),
  en:                  z.string().default(''),
  short_name:          z.string().nullish(),
  description:         z.string().nullish(),
  department:          z.string().nullish(),
  active:              z.boolean().default(true),
  contact_staff:       z.boolean().default(false),
  popular:             z.boolean().default(false),
  price:               z.coerce.number().nonnegative().optional().nullable(),
  tat_minutes:         z.string().nullish(),
  urgent_tat_minutes:  z.string().nullish(),
  available_24hr:      z.boolean().default(false),
  service:             z.string().nullish(),
  method:              z.string().nullish(),
  instrument:          z.string().nullish(),
  methodology_note:    z.string().nullish(),
  tube:                z.string().nullish(),
  tube_color:          z.string().nullish(),
  volume:              z.string().nullish(),
  stability:           z.string().nullish(),
  transport_condition: z.string().nullish(),
  reject:              z.string().nullish(),
  specimen_note:       z.string().nullish(),
  cgd:                 z.string().nullish(),
  loinc:               z.string().nullish(),
  contact_name:        z.string().nullish(),
  contact_phone:       z.string().nullish(),
  contact_email:       z.string().nullish(),
  contact_note:        z.string().nullish(),
  ref:                 z.string().nullish(),
  ref_note:            z.string().nullish(),
  related_doc_ids:     z.array(z.string()).optional(),
  related_doc_access:  z.record(z.enum(['view', 'download', 'both'])).optional(),
})

export const referenceRangeSchema = z.object({
  id:          z.number().optional(),
  gender:      z.enum(['M', 'F', 'All']).default('All'),
  min_age:     z.coerce.number().nonnegative().optional().nullable(),
  max_age:     z.coerce.number().nonnegative().optional().nullable(),
  lower_limit: z.coerce.number().optional().nullable(),
  upper_limit: z.coerce.number().optional().nullable(),
  unit:        z.string().optional(),
  note:        z.string().optional(),
  sort_order:  z.number().int().default(0),
})

export type TestFormData      = z.infer<typeof testSchema>
export type ReferenceRangeRow = z.infer<typeof referenceRangeSchema>
